name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        project: [chromium, webkit]
    steps:
      - uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js with Version set in .nvmrc
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup Playwright
        uses: ./.github/workflows/setup-playwright
        with:
          browser: ${{ matrix.project }}

      - name: Run linter
        run: pnpm run lint

      - name: Run build
        run: pnpm run build

      - name: Install HTML Parser - Tidy
        run: sudo apt-get install -y tidy

      - name: Validate HTML Files
        run: find dist -name '*.html' -exec tidy -q -e {} \;

      - name: Run unit tests
        run: pnpm run test.unit.ci

      - name: Run E2E tests for ${{ matrix.project }}
        run: pnpm exec playwright test --project="${{ matrix.project }}"
